export enum PermissionType {
    ALL='ALL',
    CAN_EDIT_USER="CAN_EDIT_USER",
    CAN_EDIT_PROFILE="CAN_EDIT_PROFILE",
    CAN_EDIT_ROLE="CAN_EDIT_ROLE",
    CAN_SEE_ANALYTICS="CAN_SEE_ANALYTICS",
}
